{
 "title": "gpt4freebot Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "SELECT message::jsonb -> 'from' ->> 'username' as username FROM message_history"
   },
   {
    "name": "first_name",
    "label": "first_name",
    "query": "SELECT message::jsonb -> 'from' ->> 'first_name' as first_name FROM message_history"
   },
   {
    "name": "last_name",
    "query": "SELECT message::jsonb -> 'from' ->> 'last_name' as last_name FROM message_history"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "stat",
   "description": "Total messages.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(message)\nFROM message_history\n"
    }
   ]
  },
  {
   "title": "Message last (1 week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(message)\nFROM message_history\nWHERE\n  TO_TIMESTAMP((message->> 'date')::bigint) > (CURRENT_TIMESTAMP - INTERVAL '7 DAY')\n"
    }
   ]
  },
  {
   "title": "Callback queries",
   "type": "stat",
   "description": "Total callback queries.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(callback_query)\nFROM callback_query_history\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Total users.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(user_id)\nFROM users\n"
    }
   ]
  },
  {
   "title": "Chats",
   "type": "stat",
   "description": "Total chats.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(chat_id)\nFROM chats\n"
    }
   ]
  },
  {
   "title": "Active chats (last 1 week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(chat_id)\nFROM chats\nWHERE\n  message_last_time > (CURRENT_TIMESTAMP - INTERVAL '7 DAY')"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "table",
   "description": "Message from: username/fist_name/last_name.\nIf setup all - select None.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  ROW_NUMBER() OVER (ORDER BY 1) AS id,\n  (1000 * (message->> 'date')::bigint) as Time,\n  message->'from'->>'username' as username,\n  message->'from'->>'first_name' as first_name,\n  message->'from'->>'last_name' as last_name,\n  message->'chat'->>'username' as chat_user_name,\n  message->> 'text' as text\nFROM message_history\nWHERE (\n  (message->'from'->>'username' like $username)\n  or\n  (message->'from'->>'first_name' like $first_name)\n  or\n  (message->'from'->>'last_name' like $last_name)\n)\nORDER BY id ASC \n"
    }
   ]
  },
  {
   "title": "Message total",
   "type": "timeseries",
   "description": "Message from: username/fist_name/last_name.\nIf setup all - select None.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  ROW_NUMBER() OVER (ORDER BY 1) AS id,\n  (1000 * (message->> 'date')::bigint) as Time\nFROM message_history\nWHERE (\n  (message->'from'->>'username' like $username)\n  or\n  (message->'from'->>'first_name' like $first_name)\n  or\n  (message->'from'->>'last_name' like $last_name)\n)\nORDER BY id ASC\n"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT\n  ROW_NUMBER() OVER (ORDER BY 1) AS id,\n  (1000 * (message->> 'date')::bigint) as Time\nFROM message_history\n"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  ROW_NUMBER() OVER (ORDER BY 1) AS id,\n  (1000 * (message->> 'date')::bigint) as Time,\n  message->'from'->>'username' as username,\n  message->'from'->>'first_name' as first_name,\n  message->'from'->>'last_name' as last_name,\n  message->'chat'->>'username' as chat_user_name,\n  message->> 'text' as text\nFROM message_history\nORDER BY id ASC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Callback queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\n  id,\n  (1000 * (callback_query->> 'date')::bigint) as Time\nFROM callback_query_history\nWHERE (\n  (callback_query->'from'->>'username' like '%')\n  or\n  (callback_query->'from'->>'first_name' like '%')\n  or\n  (callback_query->'from'->>'last_name' like '%')\n)\nORDER BY id ASC\n"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  id,\n  callback_query->'from'->>'username' as username,\n  callback_query->'from'->>'first_name' as first_name,\n  callback_query->'from'->>'last_name' as last_name,\n  callback_query->> 'data' as data\nFROM callback_query_history\nWHERE (\n  (callback_query->'from'->>'username' like '%')\n  or\n  (callback_query->'from'->>'first_name' like '%')\n  or\n  (callback_query->'from'->>'last_name' like '%')\n)\nORDER BY id ASC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message by username",
     "type": "table",
     "description": "Stats message by username",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT\n  message->'from'->>'username' as username,\n  count(id) as messages\nFROM message_history\n  GROUP BY message->'from'->>'username'\n"
      }
     ]
    },
    {
     "title": "Message by chats",
     "type": "table",
     "description": "Stats message by chat id",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT\n  message->'chat'->>'id' as chat_id,\n  count(id) as messages\nFROM message_history\n  GROUP BY message->'chat'->>'id'\n"
      }
     ]
    }
   ]
  }
 ]
}