---
name: General CI
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3.6.0
      - name: Flake8 check
        uses: oldtyt/docker-flake8@master
  build:
    needs: [flake8-lint]
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ghcr.io
      IMAGE_NAME: oldtyt/gpt4free_tg_bot
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Variables
        id: vars
        run: echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
      - name: Build image
        id: docker-build
        run: >-
          docker build
          -t $IMAGE_NAME
          -t $REPOSITORY_URL/$IMAGE_NAME:latest .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Image
        id: docker-push
        run: docker push --all-tags $REPOSITORY_URL/$IMAGE_NAME
