---
name: General CI PR
on:
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4.1.0
      - name: Flake8 check
        uses: oldtyt/docker-flake8@master
